import { create } from 'zustand';

// 定义健身计划类型
export interface FitnessPlan {
  id: number;
  category: string;
  name: string;
  description: string;
  suitableAge: string;
  suitableGender: string;
  trainingContent: string;
  planDay: number;
  currentDay: number;
  price: number;
  isBuy: boolean;
  cycle?: number;
}

const fitnessPlans: FitnessPlan[] = [
  {
    id: 1,
    category: '增肌',
    name: '基础增肌训练',
    description: '适用于初学者的增肌训练计划，包含哑铃训练、深蹲、卧推等。',
    suitableAge: '18-40',
    suitableGender: '男性',
    trainingContent: '哑铃卧推 3x12\n深蹲 3x10\n引体向上 3x8\n硬拉 3x10\n肩推 3x12',
    planDay: 5,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 2,
    category: '增肌',
    name: '高级增肌训练',
    description: '高强度训练，适合已有健身基础的人群，包含大重量训练、复合动作。',
    suitableAge: '20-45',
    suitableGender: '男性',
    trainingContent: '卧推 4x8\n深蹲 4x8\n硬拉 4x8\n引体向上 4x10\n臂弯举 3x12\n肩推 3x12',
    planDay: 5,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 3,
    category: '增肌',
    name: '徒手增肌计划',
    description: '不需要器械，在家即可进行的徒手训练，包括俯卧撑、引体向上等。',
    suitableAge: '16-35',
    suitableGender: '通用',
    trainingContent: '俯卧撑 4x15\n引体向上 4x10\n深蹲 4x15\n平板支撑 3x60秒\n开合跳 3x20',
    planDay: 5,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 4,
    category: '增肌',
    name: '健身房增肌计划',
    description: '系统化健身房训练，利用器械进行全身增肌。',
    suitableAge: '18-50',
    suitableGender: '男性',
    trainingContent: '器械卧推 3x12\n腿举 3x12\n杠铃划船 3x12\n肩推 3x12\n腹肌训练 3x20',
    planDay: 6,
    currentDay: 0,
    price: 89.9,
    isBuy: false,
  },
  {
    id: 5,
    category: '增肌',
    name: '爆发力训练',
    description: '提高肌肉爆发力，适合运动员及健身爱好者。',
    suitableAge: '20-40',
    suitableGender: '通用',
    trainingContent: '跳箱 3x8\n硬拉 3x10\n深蹲跳 3x12\n冲刺 3x50米\n战绳 3x30秒',
    planDay: 9,
    currentDay: 3,
    price: 100,
    isBuy: true,
  },
  {
    id: 6,
    category: '减脂',
    name: 'HIIT 高强度间歇训练',
    description: '短时间高强度燃脂训练，提高代谢率，快速减脂。',
    suitableAge: '18-45',
    suitableGender: '通用',
    trainingContent: '波比跳 30秒\n高抬腿 30秒\n开合跳 30秒\n深蹲跳 30秒\n俯卧撑 30秒',
    planDay: 9,
    currentDay: 3,
    price: 100,
    isBuy: true,
    cycle: 4,
  },
  {
    id: 7,
    category: '减脂',
    name: '有氧跑步计划',
    description: '通过科学跑步方式帮助燃烧脂肪，适合想减重的人群。',
    suitableAge: '20-50',
    suitableGender: '通用',
    trainingContent: '慢跑 5分钟热身\n中速跑 10分钟\n冲刺 30秒 x 4组\n慢跑 5分钟恢复\n拉伸',
    planDay: 9,
    currentDay: 0,
    price: 60,
    isBuy: false,
  },
  {
    id: 8,
    category: '减脂',
    name: 'Tabata 间歇训练',
    description: '超高效燃脂计划，4 分钟 1 轮，适合忙碌人群。',
    suitableAge: '18-40',
    suitableGender: '通用',
    trainingContent: '波比跳 20秒\n开合跳 20秒\n深蹲 20秒\n高抬腿 20秒\n俯卧撑 20秒',
    planDay: 9,
    currentDay: 3,
    price: 100,
    isBuy: true,
    cycle: 8,
  },
  {
    id: 9,
    category: '减脂',
    name: '跳绳燃脂计划',
    description: '每天 15-30 分钟跳绳，燃烧全身脂肪。',
    suitableAge: '16-45',
    suitableGender: '通用',
    trainingContent: '基础跳绳 5分钟\n交叉跳 3分钟\n双摇跳 3分钟\n快速跳 2分钟\n慢速跳 5分钟恢复',
    planDay: 9,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 10,
    category: '减脂',
    name: '家庭燃脂训练',
    description: '不需要健身房，在家即可完成的燃脂运动，如开合跳、深蹲等。',
    suitableAge: '18-50',
    suitableGender: '通用',
    trainingContent: '开合跳 3x30秒\n高抬腿 3x30秒\n俯卧撑 3x15\n平板支撑 3x40秒',
    planDay: 9,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 11,
    category: '瑜伽',
    name: '初级瑜伽',
    description: '适合零基础人群的入门瑜伽课程，帮助改善柔韧性。',
    suitableAge: '20-60',
    suitableGender: '女性',
    trainingContent: '呼吸练习 5分钟\n猫牛式 5分钟\n下犬式 3分钟\n战士一式 3分钟\n 婴儿式 3分钟',
    planDay: 9,
    currentDay: 0,
    price: 50,
    isBuy: false,
  },
  {
    id: 12,
    category: '瑜伽',
    name: '力量瑜伽',
    description: '提升身体力量的瑜伽练习，提高核心稳定性。',
    suitableAge: '18-50',
    suitableGender: '通用',
    trainingContent: '战士二式 3分钟\n船式 3分钟\n支撑侧板式 3分钟\n桥式 3分钟\n拉伸 5分钟',
    planDay: 9,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 13,
    category: '瑜伽',
    name: '睡前放松瑜伽',
    description: '促进睡眠的瑜伽练习，帮助缓解压力和焦虑。',
    suitableAge: '20-65',
    suitableGender: '通用',
    trainingContent: '蝴蝶式 3分钟\n婴儿式 3分钟\n脊柱扭转 3分钟\n仰卧束角式 5分钟\n冥想 5分钟',
    planDay: 6,
    currentDay: 0,
    price: 60,
    isBuy: false,
  },
  {
    id: 14,
    category: '瑜伽',
    name: '孕妇瑜伽',
    description: '专为孕妇设计的瑜伽课程，帮助孕期健康。',
    suitableAge: '20-40',
    suitableGender: '女性',
    trainingContent: '坐姿开髋 3分钟\n猫牛式 3分钟\n婴儿式 3分钟\n深呼吸训练 5分钟',
    planDay: 9,
    currentDay: 0,
    price: 130,
    isBuy: false,
  },
  {
    id: 15,
    category: '瑜伽',
    name: '脊柱健康瑜伽',
    description: '针对久坐人群，改善脊柱健康，预防腰椎问题。',
    suitableAge: '25-60',
    suitableGender: '通用',
    trainingContent: '下犬式 3分钟\n站立前屈 3分钟\n桥式 3分钟\n扭转式 3分钟',
    planDay: 9,
    currentDay: 0,
    price: 80,
    isBuy: false,
  },
  {
    id: 16,
    category: '综合训练',
    name: '全身功能性训练',
    description: '提高整体身体协调性和功能性的训练计划。',
    suitableAge: '18-50',
    suitableGender: '通用',
    trainingContent: '壶铃深蹲 3x12\n弹力带侧步 3x10\n俯身划船 3x12\n平板支撑 3x40秒',
    planDay: 7,
    currentDay: 0,
    price: 150,
    isBuy: false,
  },
  {
    id: 17,
    category: '综合训练',
    name: '马拉松训练计划',
    description: '适用于马拉松初学者的科学训练计划。',
    suitableAge: '20-50',
    suitableGender: '通用',
    trainingContent: '慢跑 10分钟\n中速跑 20分钟\n冲刺 30秒 x 3组\n拉伸',
    planDay: 5,
    currentDay: 0,
    price: 60,
    isBuy: false,
  },
  {
    id: 18,
    category: '综合训练',
    name: '户外徒步训练',
    description: '针对徒步爱好者的耐力和力量训练。',
    suitableAge: '20-55',
    suitableGender: '通用',
    trainingContent: '上坡徒步 30分钟\n快步走 10分钟\n深蹲 3x15\n拉伸',
    planDay: 7,
    currentDay: 0,
    price: 50,
    isBuy: false,
  },
  {
    id: 19,
    category: '综合训练',
    name: '拳击训练',
    description: '提高力量、敏捷性和耐力的拳击训练计划。',
    suitableAge: '18-40',
    suitableGender: '通用',
    trainingContent: '跳绳热身 5分钟\n直拳 3x12\n摆拳 3x12\n闪避练习 3x10',
    planDay: 7,
    currentDay: 0,
    price: 150,
    isBuy: false,
  },
  {
    id: 20,
    category: '综合训练',
    name: '柔术训练',
    description: '适用于巴西柔术或其他格斗训练的辅助计划。',
    suitableAge: '18-40',
    suitableGender: '通用',
    trainingContent: '地面防守 3x10\n反转练习 3x10\n扭力控制 3x12\n拉伸',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 21,
    category: '康复训练',
    name: '膝关节康复训练',
    description: '对膝关节损伤康复的人群，帮助恢复运动能力。',
    suitableAge: '30-60',
    suitableGender: '通用',
    trainingContent: '踝泵运动 3x10\n静蹲 3x10\n单腿站立训练 3x10',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 22,
    category: '康复训练',
    name: '肩颈康复训练',
    description: '适合久坐办公人群，缓解肩颈疼痛。',
    suitableAge: '25-60',
    suitableGender: '通用',
    trainingContent: '颈部拉伸 3x30秒\n肩部回旋 3x10\n肩胛骨收缩 3x10',
    planDay: 7,
    currentDay: 0,
    price: 90,
    isBuy: false,
  },
  {
    id: 23,
    category: '康复训练',
    name: '腰椎健康训练',
    description: '针对腰椎间盘突出等问题的康复训练。',
    suitableAge: '30-65',
    suitableGender: '通用',
    trainingContent: '仰卧桥式 3x10\n四点跪姿收腹 3x10\n腹肌激活练习 3x15',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 24,
    category: '康复训练',
    name: '术后康复训练',
    description: '帮助术后康复患者逐步恢复运动能力。',
    suitableAge: '30-70',
    suitableGender: '通用',
    trainingContent: '慢速步行 10分钟\n低强度拉伸 3x10\n基础核心激活练习',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 25,
    category: '康复训练',
    name: '跑步损伤康复',
    description: '适用于跑步受伤后的康复和预防性训练。',
    suitableAge: '20-50',
    suitableGender: '通用',
    trainingContent: '髋屈肌拉伸 3x30秒\n小腿拉伸 3x30秒\n单腿平衡训练 3x10',
    planDay: 7,
    currentDay: 0,
    price: 80,
    isBuy: false,
  },
  {
    id: 26,
    category: '塑形',
    name: '女性塑形训练',
    description: '适合女性的全身塑形计划，打造紧致身材。',
    suitableAge: '18-45',
    suitableGender: '女性',
    trainingContent: '臀桥 3x15\n侧卧抬腿 3x12\n深蹲 3x12\n平板支撑 3x40秒',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 27,
    category: '塑形',
    name: '腹肌雕刻训练',
    description: '专门针对腹肌塑形的训练，帮助打造六块腹肌。',
    suitableAge: '18-40',
    suitableGender: '男性',
    trainingContent: '仰卧卷腹 3x15\n侧腹扭转 3x12\n仰卧抬腿 3x12\n平板支撑 3x40秒',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 28,
    category: '塑形',
    name: '臀部塑形训练',
    description: '适合女性的翘臀训练计划，增强臀部肌肉。',
    suitableAge: '18-45',
    suitableGender: '女性',
    trainingContent: '臀桥 3x15\n箭步蹲 3x12\n壶铃深蹲 3x12\n侧卧抬腿 3x12',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 29,
    category: '塑形',
    name: '全身塑形训练',
    description: '包含全身各部位训练，提高身体美感和线条感。',
    suitableAge: '18-50',
    suitableGender: '通用',
    trainingContent: '深蹲 3x15\n俯卧撑 3x15\n平板支撑 3x40秒\n拉伸',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
  {
    id: 30,
    category: '塑形',
    name: '上半身塑形',
    description: '针对上肢和核心区域的塑形训练。',
    suitableAge: '18-50',
    suitableGender: '通用',
    trainingContent: '哑铃推举 3x12\n引体向上 3x10\n仰卧卷腹 3x15',
    planDay: 7,
    currentDay: 0,
    price: 100,
    isBuy: false,
  },
];

interface FitnessState {
  fitnessData: FitnessPlan[];
  setFitnessData: (data: FitnessPlan[]) => void;
  updateFitnessData: (id: number, data: FitnessPlan) => void;
}

export const useFitnessStore = create<FitnessState>((set) => ({
  fitnessData: fitnessPlans,
  setFitnessData: (data: any) => set({ fitnessData: data }),
  updateFitnessData: (id: number, data: FitnessPlan) =>
    set((state) => ({
      fitnessData: state.fitnessData.map((item) => (item.id === id ? data : item)),
    })),
}));
